remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Lars Gudjons Portfolio
description: My Portfolio Website
logo: /assets/img/logo.jpg
show_downloads: true


# add a list of all my projects
# projects:
#   - title: "Project 1"
#     description: "This is a description of project 1"
#     image: /assets/img/project1.png
#     url: https://www.example.com
#   - title: "Project 2"
#     description: "This is a description of project 2"
#     image: /assets/img/project2.png
#     url: https://www.example.com

